import { describe, expect, it } from "vitest";
// @ts-expect-error Node types are not included in the browser-focused tsconfig.
import { execFileSync } from "node:child_process";
// prettier-ignore
// @ts-expect-error Node fixture helpers exceed the minimal filesystem declarations.
import { lstat, mkdir, mkdtemp, readFile, rm, symlink, writeFile } from "node:fs/promises";
// @ts-expect-error Node types are not included in the browser-focused tsconfig.
import { tmpdir } from "node:os";
// @ts-expect-error Node executable is not included in the minimal process declaration.
import { execPath } from "node:process";
import path from "node:path";

async function fixture() {
  const root = await mkdtemp(path.join(tmpdir(), "aic-portable-sync-"));
  const source = path.join(root, "source");
  const target = path.join(root, "aic-notes");
  for (const name of [
    "source/scripts",
    "source/src",
    "source/pwa",
    "source/public",
    "source/dist-pwa/assets",
    "aic-notes/vendor",
  ])
    await mkdir(path.join(root, name), { recursive: true });
  await writeFile(
    path.join(source, "scripts/sync-portable-runtime.mjs"),
    await readFile(path.resolve("scripts/sync-portable-runtime.mjs"), "utf8"),
  );
  await writeFile(
    path.join(source, "package.json"),
    JSON.stringify({
      name: "standard-notes-aic-editor",
      type: "module",
      version: "47.1.0",
    }),
  );
  await writeFile(
    path.join(target, "package.json"),
    JSON.stringify({ name: "aic-notes" }),
  );
  await writeFile(path.join(source, ".gitignore"), "dist-pwa/\n");
  await writeFile(
    path.join(source, "src/entry.js"),
    "export const fixture = 1;\n",
  );
  await writeFile(path.join(source, "pwa/index.html"), "source fixture\n");
  await writeFile(
    path.join(source, "vite.pwa.config.mjs"),
    "export default {};\n",
  );
  await writeFile(
    path.join(source, "dist-pwa/index.html"),
    '<script type="module" src="./assets/entry.js"></script>',
  );
  await writeFile(
    path.join(source, "dist-pwa/assets/entry.js"),
    "export const fixture = 1;\n",
  );
  const git = (...args: string[]) =>
    execFileSync(
      "git",
      [
        "-c",
        "core.hooksPath=/dev/null",
        "-c",
        "commit.gpgsign=false",
        "-c",
        "user.name=Fixture",
        "-c",
        "user.email=fixture@example.invalid",
        ...args,
      ],
      { cwd: source, encoding: "utf8" },
    ).trim();
  git("init", "--quiet");
  git("add", ".");
  git("commit", "--quiet", "-m", "Fixture canonical source");
  const run = (...args: string[]) =>
    execFileSync(
      execPath,
      [path.join(source, "scripts/sync-portable-runtime.mjs"), ...args],
      { cwd: source, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] },
    );
  const snapshotPath = path.join(target, "PORTABLE_SNAPSHOT.json");
  const snapshot = async () => JSON.parse(await readFile(snapshotPath, "utf8"));
  return {
    root,
    source,
    target,
    git,
    run,
    snapshot,
    snapshotPath,
    dispose: () => rm(root, { recursive: true, force: true }),
  };
}

describe("canonical portable runtime distribution", () => {
  it("copies exact built files, records committed provenance, and keeps --check read-only", async () => {
    const f = await fixture();
    try {
      f.run();
      const snapshot = await f.snapshot();
      expect(snapshot.format).toBe("aic-portable-runtime");
      expect(snapshot.version).toBe(1);
      expect(snapshot.sourceCommit).toBe(f.git("rev-parse", "HEAD"));
      expect(snapshot.sourceState).toBeUndefined();
      expect(Object.keys(snapshot.hashes)).toEqual([
        "assets/entry.js",
        "index.html",
      ]);
      const vendorEntry = path.join(
        f.target,
        "vendor/portable-runtime/assets/entry.js",
      );
      expect(await readFile(vendorEntry, "utf8")).toBe(
        await readFile(path.join(f.source, "dist-pwa/assets/entry.js"), "utf8"),
      );
      const before = (await lstat(f.snapshotPath)).mtimeMs;
      f.run("--check", "--target", f.target);
      expect((await lstat(f.snapshotPath)).mtimeMs).toBe(before);
      expect(f.git("status", "--porcelain")).toBe("");
      await writeFile(
        path.join(f.source, "src/entry.js"),
        "export const fixture = 2;\n",
      );
      expect(() => f.run("--check", "--target", f.target)).toThrow();
      f.run("--target", f.target);
      expect((await f.snapshot()).sourceState).toBe("working-tree");
      expect((await f.snapshot()).sourceCommit).toBe(snapshot.sourceCommit);
    } finally {
      await f.dispose();
    }
  });

  it("marks untracked source/config changes and detects altered generated bytes", async () => {
    const f = await fixture();
    try {
      await writeFile(
        path.join(f.source, "src/new-import.js"),
        "export const fixture = 3;\n",
      );
      f.run("--target", f.target);
      expect((await f.snapshot()).sourceState).toBe("working-tree");
      await writeFile(
        path.join(f.target, "vendor/portable-runtime/assets/entry.js"),
        "changed generated content\n",
      );
      expect(() => f.run("--check", "--target", f.target)).toThrow();
      expect(() => f.run("--target", f.target)).toThrow();
      expect(
        await readFile(
          path.join(f.target, "vendor/portable-runtime/assets/entry.js"),
          "utf8",
        ),
      ).toBe("changed generated content\n");
    } finally {
      await f.dispose();
    }
  });

  it("removes only previously owned obsolete assets and refuses unrelated files", async () => {
    const f = await fixture();
    try {
      const oldAsset = path.join(f.source, "dist-pwa/assets/obsolete.js");
      await writeFile(oldAsset, "obsolete generated content\n");
      f.run("--target", f.target);
      await rm(oldAsset);
      f.run("--target", f.target);
      await expect(
        lstat(
          path.join(f.target, "vendor/portable-runtime/assets/obsolete.js"),
        ),
      ).rejects.toThrow();
      const unrelated = path.join(
        f.target,
        "vendor/portable-runtime/personal.txt",
      );
      await writeFile(unrelated, "preserve this unrelated fixture\n");
      const before = await readFile(f.snapshotPath, "utf8");
      expect(() => f.run("--target", f.target)).toThrow();
      expect(await readFile(unrelated, "utf8")).toBe(
        "preserve this unrelated fixture\n",
      );
      expect(await readFile(f.snapshotPath, "utf8")).toBe(before);
    } finally {
      await f.dispose();
    }
  });

  it("rejects populated unowned directories, symlink markers, and remote build resources", async () => {
    const f = await fixture();
    try {
      await mkdir(path.join(f.target, "vendor/portable-runtime"));
      const unrelated = path.join(
        f.target,
        "vendor/portable-runtime/owner.txt",
      );
      await writeFile(unrelated, "preserve fixture\n");
      expect(() => f.run("--target", f.target)).toThrow();
      await rm(unrelated);
      const external = path.join(f.root, "external-snapshot.json");
      await writeFile(external, "preserve marker fixture\n");
      await symlink(external, f.snapshotPath);
      expect(() => f.run("--target", f.target)).toThrow();
      expect(await readFile(external, "utf8")).toBe(
        "preserve marker fixture\n",
      );
      await rm(f.snapshotPath);
      await writeFile(
        path.join(f.source, "dist-pwa/index.html"),
        '<script type="module" src="./assets/entry.js"></script><script src="https://example.invalid/remote.js"></script>',
      );
      expect(() => f.run("--target", f.target)).toThrow();
    } finally {
      await f.dispose();
    }
  });
});
